DATASET:
  root_dataset: "./data/HOT"
  list_train: "./data/hot_train.odgt"
  list_val: "./data/hot_validation.odgt"
  list_test: "./data/hot_test.odgt"
  num_class: 18
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "resnet50dilated"
  arch_decoder: "c1"
  fc_dim: 2048
  with_part: True

TRAIN:
  batch_size_per_gpu: 4
  num_epoch: 100
  start_epoch: 0
  epoch_iters: 2000
  lr_encoder: 0.00001
  lr_decoder: 0.00001
  lr_pow: 0.9
  beta1: 0.9
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

DIR: "ckpt/hot-c1"
